CREATE DATABASE IAM_BOCATA_BD;

USE IAM_BOCATA_BD;

CREATE TABLE USERS (
    ID_USER INTEGER PRIMARY KEY AUTO_INCREMENT,
    GOOGLE_ID VARCHAR(25) UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255),
    MAIL VARCHAR(150) NOT NULL UNIQUE,
    PHOTOPATH VARCHAR(255),
    QRPHOTOPATH VARCHAR(255) UNIQUE,
    REGISTER_DATE DATETIME NOT NULL,
    MONEY DOUBLE(4,2) NOT NULL,
    PERMISSION_LEVEL INTEGER NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    IS_GOOGLE_USER BOOLEAN NOT NULL
);

CREATE TABLE CATEGORIES (
    ID_CATEGORY INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50)
);

CREATE TABLE PRODUCTS (
    ID_PRODUCT INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PHOTOPATH VARCHAR(255),
    PRICE DOUBLE(4,2) NOT NULL,
    PRICE_OFTHEDAY DOUBLE(4,2) NOT NULL,
    DATE_ADDED DATETIME NOT NULL,
    INGREDIENTS VARCHAR(255) NOT NULL,
    ID_CATEGORY INTEGER NOT NULL,
    ENABLED INTEGER NOT NULL,
    OFTHEDAY BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE PRODUCTS ADD FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES(ID_CATEGORY);

CREATE TABLE LIKES (
    ID_LIKE INTEGER AUTO_INCREMENT,
    ID_USER INTEGER NOT NULL,
    ID_PRODUCT INTEGER NOT NULL,
    PRIMARY KEY (ID_USER, ID_PRODUCT)
);

ALTER TABLE LIKES ADD FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER);
ALTER TABLE LIKES ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS(ID_PRODUCT);

CREATE TABLE BUY (
    ID_BUY INTEGER NOT NULL,
    ID_CHECKOUT INTEGER NOT NULL,
    STATE VARCHAR(20) NOT NULL,
    BUYDATE DATETIME NOT NULL,
    DATE_DELIVERY DATETIME NOT NULL,
    ID_USER INTEGER NOT NULL,
    ID_PRODUCT INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    TOTAL DOUBLE(4,2) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_BUY, ID_CHECKOUT)
);

ALTER TABLE BUY ADD FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER);
ALTER TABLE BUY ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS(ID_PRODUCT);

CREATE TABLE SESSIONS (
    ID_SESSION INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_USER INTEGER NOT NULL,
    LOGINDATE DATETIME,
    IP VARCHAR(16) NOT NULL,
    DEVICE VARCHAR(6) NOT NULL
);

ALTER TABLE SESSIONS ADD FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER);

CREATE TABLE PARAMETERS (
    ID_PARAMETER INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    VALUE VARCHAR(255) NOT NULL
);

-- PARAMETERS VALUES
INSERT INTO PARAMETERS (NAME, VALUE) VALUES
    ('TIME_OPEN', '9:30'),
    ('TIME_CLOSE', '19:00'),
    ('MARGIN_MIN', '10'),
    ('RUNNING', 'FALSE');

-- INFO DE EJEMPLO

INSERT INTO CATEGORIES (NAME) VALUES ('Entrepans');
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, PHOTOPATH, DATE_ADDED, INGREDIENTS, ID_CATEGORY, ENABLED)
    VALUES ('Biquini', 'Biquini', 2.2, '', NOW(), 'Pa-Pernil dolç-Formatge', 1, TRUE ),
        ('Bacon Queso', 'Bacon Queso', 2.2, '', NOW(), 'Pa-Bacon-Formatge', 1, TRUE );

INSERT INTO USERS (NAME, PASSWORD, MAIL, PHOTOPATH, QRPHOTOPATH, REGISTER_DATE, MONEY, PERMISSION_LEVEL, ENABLED) VALUES
    ('admin', 'admin', 'iambocata@iam.cat', '',
    '', NOW(), 0, 1, TRUE );

-- QUERIES TEST

SELECT P.ID_PRODUCT, P.NAME, P.DESCRIPTION, P.PRICE, P.PHOTOPATH, P.DATE_ADDED, P.INGREDIENTS, C.NAME AS CATEGORY
FROM PRODUCTS P JOIN CATEGORIES C ON P.ID_CATEGORY=C.ID_CATEGORY
WHERE P.ENABLED=1
